
#   export AM_HOME=...../codes/os/code/abstract-machine  绝对路径
#  make -f 00-Makefile    ARCH=native   run


# NAME = kernel
# SRCS = thread-os.c
# include $(AM_HOME)/Makefile


# NAME = hello
# SRCS = hello-am.c
# include $(AM_HOME)/Makefile


NAME = kernel
SRCS = test1.c
include $(AM_HOME)/Makefile
